In [1]:
import torch
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt

In [4]:
random_tensor = torch.rand(5,5)
random_tensor

tensor([[0.7093, 0.8961, 0.6523, 0.2566, 0.4123],
        [0.3050, 0.3009, 0.2924, 0.1853, 0.9949],
        [0.5225, 0.6590, 0.1740, 0.7266, 0.7634],
        [0.6698, 0.2935, 0.8800, 0.7876, 0.1579],
        [0.7381, 0.4492, 0.6254, 0.1283, 0.1507]])

In [3]:
random_tensor * 100

tensor([[59.6066, 74.4578, 58.9445, 17.7223, 21.7215],
        [ 6.5286,  2.5044,  7.1234, 64.6138, 61.4259],
        [ 7.0390, 57.2257, 85.4152, 89.6138, 18.9219],
        [76.8051, 30.7679, 99.8912, 87.8414, 34.3792],
        [10.1072, 16.9034,  8.2480, 19.3110, 39.9815]])

In [13]:
rand_img_tensor = torch.rand(224, 224, 3)

In [14]:
tt = torch.tensor([[1,2,3],[4,5,6],[7,8,9]], dtype=torch.int32)

In [16]:
tt.shape, tt.dtype

(torch.Size([3, 3]), torch.int32)

In [22]:
ss = torch.full((3,3), 4, dtype=torch.int16)
ss.shape, ss.dtype

(torch.Size([3, 3]), torch.int16)

In [23]:
ss * tt

tensor([[ 4,  8, 12],
        [16, 20, 24],
        [28, 32, 36]], dtype=torch.int32)

In [21]:
ss.device

device(type='cpu')

In [28]:
torch.eye(5) + torch.tensor([2,4,6,4,2], dtype=torch.int16)

tensor([[3., 4., 6., 4., 2.],
        [2., 5., 6., 4., 2.],
        [2., 4., 7., 4., 2.],
        [2., 4., 6., 5., 2.],
        [2., 4., 6., 4., 3.]])