In [1]:
import numpy as np

In [10]:
a = np.array([[6, 5, 4, 3, 2, 1], [0, 9, 8, 7, 6, 5]], dtype="int16")
print(a)

[[6 5 4 3 2 1]
 [0 9 8 7 6 5]]


In [6]:
print(a.ndim)
print(a.shape)

2
(2, 6)


In [11]:
print(a.dtype)

int16


In [12]:
print(a.itemsize)
print(a.size)

2
12


In [21]:
print(a[1])
print(a[1, 3])
print(a[:, ::2])

[0 9 8 7 6 5]
7
[[6 4 2]
 [0 8 6]]


In [23]:
b = np.array([
    [
        [1, 2, 3],
        [4, 5, 6]
    ],
    [
        [7, 8, 9],
        [10, 11, 12]
    ]
])
b.shape

(2, 2, 3)

In [25]:
c = np.zeros((2, 3, 3, 2))
c

array([[[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]]])

In [26]:
d = np.ones((2, 3, 3, 2))
d

array([[[[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]]],


       [[[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]]]])

In [28]:
e = np.full((2, 3, 3, 2), 9)
e

array([[[[9, 9],
         [9, 9],
         [9, 9]],

        [[9, 9],
         [9, 9],
         [9, 9]],

        [[9, 9],
         [9, 9],
         [9, 9]]],


       [[[9, 9],
         [9, 9],
         [9, 9]],

        [[9, 9],
         [9, 9],
         [9, 9]],

        [[9, 9],
         [9, 9],
         [9, 9]]]])

In [29]:
f = np.full_like(c, 6)
f

array([[[[6, 6],
         [6, 6],
         [6, 6]],

        [[6, 6],
         [6, 6],
         [6, 6]],

        [[6, 6],
         [6, 6],
         [6, 6]]],


       [[[6, 6],
         [6, 6],
         [6, 6]],

        [[6, 6],
         [6, 6],
         [6, 6]],

        [[6, 6],
         [6, 6],
         [6, 6]]]])

In [30]:
g = np.random.rand(2, 3, 3, 2)
g

array([[[[0.54289251, 0.68105541],
         [0.49662588, 0.59140636],
         [0.0360063 , 0.1218568 ]],

        [[0.9212556 , 0.02768147],
         [0.31453718, 0.0851331 ],
         [0.25926929, 0.42768863]],

        [[0.91561711, 0.71562853],
         [0.91157747, 0.72350442],
         [0.97036439, 0.6516958 ]]],


       [[[0.56407688, 0.85737469],
         [0.94308462, 0.76995881],
         [0.37950159, 0.63015394]],

        [[0.1213155 , 0.88120209],
         [0.2656372 , 0.44649797],
         [0.45927745, 0.05617243]],

        [[0.94367937, 0.84144246],
         [0.30127859, 0.91251993],
         [0.66159788, 0.66190897]]]])

In [33]:
h = np.random.random_sample(c.shape)
h

array([[[[0.86053542, 0.29876174],
         [0.80100032, 0.55656858],
         [0.66205133, 0.91552791]],

        [[0.39328423, 0.58993818],
         [0.02408923, 0.61729465],
         [0.55628638, 0.42096587]],

        [[0.07093536, 0.63262191],
         [0.45986981, 0.33124722],
         [0.45669953, 0.26688291]]],


       [[[0.44711088, 0.60254035],
         [0.04024992, 0.09437891],
         [0.28685748, 0.03253319]],

        [[0.52300015, 0.27811057],
         [0.9407229 , 0.98252102],
         [0.76777731, 0.76818707]],

        [[0.88191529, 0.33168376],
         [0.91559392, 0.5163688 ],
         [0.07593302, 0.43304456]]]])

In [34]:
i = np.random.randint(2, size=(3, 3))
i

array([[0, 1, 1],
       [1, 0, 1],
       [1, 1, 1]])

In [35]:
j = np.identity(5)
j

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [37]:
arr = np.array([[1, 2, 3]])
k = np.repeat(arr, 3, axis=0)
k

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [40]:
output = np.ones((5, 5))
output
zeroes = np.zeros((3, 3))
zeroes[1,1] = 9
zeroes
output[1:-1, 1:-1] = zeroes
output

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [42]:
l = np.array([1, 2, 3])
m = l
m[0] = 9
print(m)
print(l)

[9 2 3]
[9 2 3]


In [43]:
l = np.array([1, 2, 3])
m = l.copy()
m[0] = 9
print(m)
print(l)

[9 2 3]
[1 2 3]


In [44]:
l + 2

array([3, 4, 5])

In [45]:
l * 3

array([3, 6, 9])

In [46]:
l / 2

array([0.5, 1. , 1.5])

In [47]:
l ** 3

array([ 1,  8, 27])

In [48]:
np.sin(l)

array([0.84147098, 0.90929743, 0.14112001])

In [49]:
np.cos(l)

array([ 0.54030231, -0.41614684, -0.9899925 ])

In [50]:
# https://docs.scipy.org/doc/numpy/reference/routines.math.html
# for all the regular math possibilities...

##### Linear Algebra

In [52]:
aa = np.ones((2,3))
ba = np.full((3,2), 2)
aa, ba

(array([[1., 1., 1.],
        [1., 1., 1.]]),
 array([[2, 2],
        [2, 2],
        [2, 2]]))

In [53]:
np.matmul(aa, ba)

array([[6., 6.],
       [6., 6.]])

In [55]:
ca = np.identity(3)
np.linalg.det(ca)

1.0

In [56]:
# https://docs.scipy.org/doc/numpy/reference/routines.linalg.html
# for all the linear algebra possibilities...

##### Statistics

In [57]:
bb = np.array([[1,2,3], [4,5,6]])
bb

array([[1, 2, 3],
       [4, 5, 6]])

In [60]:
np.min(bb), np.min(bb, axis=0), np.min(bb, axis=1)

(1, array([1, 2, 3]), array([1, 4]))

In [61]:
np.max(bb), np.max(bb, axis=0), np.max(bb, axis=1)

(6, array([4, 5, 6]), array([3, 6]))

In [62]:
np.sum(bb), np.sum(bb, axis=0), np.sum(bb, axis=1)

(21, array([5, 7, 9]), array([ 6, 15]))

##### Reorganizing Arrays

In [63]:
before = np.array([[1,2,3,4],[5,6,7,8]])
before

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [64]:
before.reshape((8,1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [66]:
before.reshape((2,2,2))

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [67]:
# reshape must have the same number of elements
before.reshape((3,3))

ValueError: cannot reshape array of size 8 into shape (3,3)

In [69]:
# Vertically stack vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1, v2]), np.vstack([v1, v2, v1, v2])

(array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[1, 2, 3, 4],
        [5, 6, 7, 8],
        [1, 2, 3, 4],
        [5, 6, 7, 8]]))

In [72]:
# Horizontally stacking vectors
h1 = np.ones((2, 4))
h2 = np.zeros((2,2))

np.hstack([h1, h2]), np.hstack([h1, h2, h1])

(array([[1., 1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0., 0.]]),
 array([[1., 1., 1., 1., 0., 0., 1., 1., 1., 1.],
        [1., 1., 1., 1., 0., 0., 1., 1., 1., 1.]]))

##### Miscellaneous

*Load data from file*

In [77]:
file_data = np.genfromtxt('../data/data.txt', delimiter=',', dtype='int16')
file_data

array([[20,  1, 20,  1, 20,  0, 20,  0],
       [23,  1, 23,  1, 21,  0, 21,  0],
       [25,  1, 25,  1, 25,  0, 25,  0],
       [26,  1, 26,  1, 26,  0, 26,  0],
       [29,  1, 29,  1, 27,  0, 27,  0],
       [30,  1, 30,  1, 30,  0, 30,  0],
       [31,  1, 31,  1, 31,  0, 31,  0],
       [33,  1, 33,  1, 34,  0, 34,  0],
       [37,  1, 37,  1, 35,  0, 35,  0]], dtype=int16)

##### Boolean Masking and Advanced Indexing

In [79]:
file_data > 5

array([[ True, False,  True, False,  True, False,  True, False],
       [ True, False,  True, False,  True, False,  True, False],
       [ True, False,  True, False,  True, False,  True, False],
       [ True, False,  True, False,  True, False,  True, False],
       [ True, False,  True, False,  True, False,  True, False],
       [ True, False,  True, False,  True, False,  True, False],
       [ True, False,  True, False,  True, False,  True, False],
       [ True, False,  True, False,  True, False,  True, False],
       [ True, False,  True, False,  True, False,  True, False]])

In [80]:
file_data[file_data > 5]

array([20, 20, 20, 20, 23, 23, 21, 21, 25, 25, 25, 25, 26, 26, 26, 26, 29,
       29, 27, 27, 30, 30, 30, 30, 31, 31, 31, 31, 33, 33, 34, 34, 37, 37,
       35, 35], dtype=int16)

In [81]:
file_data[[1, 3, 5]]

array([[23,  1, 23,  1, 21,  0, 21,  0],
       [26,  1, 26,  1, 26,  0, 26,  0],
       [30,  1, 30,  1, 30,  0, 30,  0]], dtype=int16)

In [82]:
np.any(file_data > 20, axis=1)

array([False,  True,  True,  True,  True,  True,  True,  True,  True])

In [83]:
((file_data > 20) & (file_data < 30))

array([[False, False, False, False, False, False, False, False],
       [ True, False,  True, False,  True, False,  True, False],
       [ True, False,  True, False,  True, False,  True, False],
       [ True, False,  True, False,  True, False,  True, False],
       [ True, False,  True, False,  True, False,  True, False],
       [False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False]])

In [88]:
# selecting a 'diagonal'
file_data[[3, 4, 5], [0, 1, 2]]

array([26,  1, 30], dtype=int16)

In [89]:
file_data[3:5, 0:3]

array([[26,  1, 26],
       [29,  1, 29]], dtype=int16)

In [94]:
file_data[[0,7,8], 6:]

array([[20,  0],
       [34,  0],
       [35,  0]], dtype=int16)